// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/[name].tsx";
import * as $1 from "./routes/api/proxy/index.ts";
import * as $2 from "./routes/extension/[uuid].tsx";
import * as $3 from "./routes/index.tsx";
import * as $$0 from "./islands/Counter.tsx";
import * as $$1 from "./islands/comments.tsx";
import * as $$2 from "./islands/extensions.tsx";
import * as $$3 from "./islands/searchForm.tsx";

const manifest = {
  routes: {
    "./routes/[name].tsx": $0,
    "./routes/api/proxy/index.ts": $1,
    "./routes/extension/[uuid].tsx": $2,
    "./routes/index.tsx": $3,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
    "./islands/comments.tsx": $$1,
    "./islands/extensions.tsx": $$2,
    "./islands/searchForm.tsx": $$3,
  },
  baseUrl: import.meta.url,
};

export default manifest;
